name: Fetch Sophos IoCs

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-iocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing commits
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install iocparser

      - name: Run IoC fetcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automatically provided by GitHub
        run: python scripts/fetch_iocs.py  # Assuming script is in scripts directory

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Sophos IoCs"
          file_pattern: 'latest_commit.txt sophos_iocs.txt'